name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build image
      run: docker build . --file Dockerfile --tag kevinpan45/graalvm21-python:0.0.2
    - name: Push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kevinpan45/iot-biz:latest
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
