name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . --file Dockerfile --tag kevinpan45/graalvm21-python:0.0.2
    - name: Push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kevinpan45/graalvm21-python:0.0.2
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
