name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: kevinpan45/graalvm21-python
        # Tags override for Docker image
        tags: 0.0.2
        # Target Docker registry
        registry: index.docker.io
        # Docker registry username
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        # Docker registry password
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
